CREATE TABLE Exemplaires(
  id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  oeuvre_id NUMBER(19, 0),
  numero_serie VARCHAR2(50),
  CONSTRAINT fk_exemplaire_oeuvre
    FOREIGN KEY (oeuvre_id)
    REFERENCES Oeuvres(id)
)

 


CREATE OR REPLACE TYPE Exemplaire_type as OBJECT(
  id NUMBER(19, 0),
  nom VARCHAR2(50),

  CONSTRUCTOR FUNCTION Author_type (id NUMBER, nom VARCHAR2) RETURN SELF AS RESULT,
  MEMBER PROCEDURE sauvegarder,
  MEMBER PROCEDURE supprimer
);

CREATE TABLE Exemplaire of Exemplaire_type;
 
ALTER TABLE Exemplaire
ADD CONSTRAINT pk_genre
    PRIMARY KEY (id);


CREATE OR REPLACE TYPE BODY Exemplaire_type AS 
  
  CONSTRUCTOR FUNCTION Exemplaire_type (id NUMBER, nom VARCHAR2)
  RETURN SELF AS RESULT IS
  BEGIN
    SELF.id := id 
    SELF.nom := nom
  END;

  MEMBER PROCEDURE sauvegarder IS
  BEGIN
    INSERT INTO Exemplaire('id', 'nom') VALUES (SELF.id, SELF.nom);
    COMMIT;
  END sauvegarder;

  MEMBER PROCEDURE supprimer IS
  BEGIN
    DELETE FROM Exemplaire as exmp where exmp.id = SELF.id;
    COMMIT;
  END supprimer;

 
  STATIC FUNCTION getExemplaire(exmp_id NUMBER) 
  Return Exemplaire_type IS
    exmp Exemplaire_type
  BEGIN
    SELECT Exemplaire_type(a.id, a.nom) into exmp From Exemplaire as a where  a.id = exmp_id;
    COMMIT;
    return exmp;
  END getExemplaire;

END; 