-- Oeuvre_type
--   sauvegarder
--   supprimer
--   getAuthor
--   getGenre
--   getExemplaires
--   ::getOeuvre(id)

CREATE TABLE Oeuvres(
  id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titre VARCHAR2(50),
  author_id NUMBER(19, 0),
  genre_id NUMBER(19, 0)
  CONSTRAINT fk_oeuvres_author
    FOREIGN KEY (author_id)
    REFERENCES Abonnes(id), 
  CONSTRAINT fk_oeuvres_genre
    FOREIGN KEY (genre_id)
    REFERENCES Genres(id)
)